#!/bin/bash
# This hook is run after a new virtualenv is activated.
# https://gist.github.com/2042882
#
# http://stackoverflow.com/questions/1961997/\
# is-it-possible-to-add-pyqt4-pyside-packages-on-a-virtualenv-
# sandbox/9716100#9716100

LIBS=( PyQt4 sip.so )

PYTHON_VERSION=python$(python -c "import sys; print (str(sys.version_info[0])+'.'+str(sys.version_info[1]))")
VAR=( $(which -a $PYTHON_VERSION) )

GET_PYTHON_LIB_CMD="from distutils.sysconfig import get_python_lib; print (get_python_lib())"
LIB_VIRTUALENV_PATH=$(python -c "$GET_PYTHON_LIB_CMD")
LIB_SYSTEM_PATH=$(${VAR[-1]} -c "$GET_PYTHON_LIB_CMD")

for LIB in ${LIBS[@]}
do
    ln -s $LIB_SYSTEM_PATH/$LIB $LIB_VIRTUALENV_PATH/$LIB 
done

# workaround for odd problem installing pastescript first
for p in Paste-1.7.5.1.tar.gz PasteDeploy-1.5.0.tar.gz PasteScript-1.7.5.tar.gz; do
    pip install http://cypress/python/$p
done

#for p in pip-1.4.1.tar.gz setuptools-1.1.6.tar.gz distribute-0.7.3.zip ;
#do
#    pip install http://cypress/python/$p
#done

pip install http://cypress/python/pip-1.4.1.tar.gz

pip install http://cypress/python/setuptools-1.1.6.tar.gz
pip install --no-index -f http://cypress/python http://cypress/python/distribute-0.7.3.zip

#pip install --no-index -f http://cypress/python/webapp http://cypress/python/webapp/pyramid_deform-0.2a5.tar.gz

#pip install --no-index -f http://cypress/python/webapp http://cypress/python/webapp/vobject-0.8.1c.tar.gz

#pip install --no-index -f http://cypress/python/webapp http://cypress/python/webapp/fanstatic-1.0a2.zip

#pip install --no-index -f http://cypress/python/webapp http://cypress/python/webapp/trumpet-0.1.1dev.zip


